spring:
  jpa:
    database: postgresql
    open-in-view: false
    show-sql: ${JPA_SHOW_SQL:false}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.order_inserts: ${HIBERNATE_ORDER_INSERTS:true}
      hibernate.jdbc.batch_size: ${HIBERNATE_JDBC_BATCH_SIZE:50}
      hibernate.jdbc.fetch_size: ${HIBERNATE_JDBC_FETCH_SIZE:1000}
      hibernate.jdbc.batch_versioned_data: ${HIBERNATE_JDBC_BATCH_VERSIONED:true}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:none}
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATASOURCE_USERNAME:spring_integration_api_app_usr}
    password: ${DATASOURCE_PASSWORD:123}
    hikari:
      minimum-idle: ${HIKARI_MIN_IDLE_SIZE:2}
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:10}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT:180000}
      max-lifetime: ${HIKARI_MAX_LIFETIME:300000}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:20000}
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    user: ${FLYWAY_USER:postgres}
    password: ${FLYWAY_PASSWORD:postgres}
    url: ${spring.datasource.url}
    schemas: ${FLYWAY_SCHEMAS:spring_integration_api_app_adm}
    placeholders:
      pw.spring_integration_api_app_adm_pwd: ${FLYWAY_APP_ADM_PASSWORD:'123'}
      pw.spring_integration_api_app_usr_pwd: ${FLYWAY_APP_USR_PASSWORD:'123'}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:erhan.canlica@gmail.com}
    password: ${MAIL_PASSWORD:vyxc dubn ekqg auxq}
    properties:
      mail.smtp.auth: ${MAIL_STMP_AUTH:true}
      mail.smtp.starttls.enable: ${MAIL_STMP_STARTTLS_ENABLE:true}

spring-integration:
  flow:
    createdEmailIntegrationThreadPool: ${CREATED_EMAIL_INTEGRATION_THREAD_POOL:2}
    pendingEmailIntegrationThreadPool: ${PENDING_EMAIL_INTEGRATION_THREAD_POOL:2}
    deliveryEmailIntegrationThreadPool: ${DELIVERY_EMAIL_INTEGRATION_THREAD_POOL:2}
    checkoutEmailIntegrationThreadPool: ${CHECKOUT_EMAIL_INTEGRATION_THREAD_POOL:2}
    notificationEmailIntegrationThreadPool: ${NOTIFICATION_EMAIL_INTEGRATION_THREAD_POOL:2}
    createdStatusEmailPollerMetadataFixedDelayInSecond: ${CREATED_STATUS_EMAIL_POLLER_METADATA_FIXED_DELAY_IN_SECOND:10}
    pendingStatusEmailPollerMetadataFixedDelayInSecond: ${PENDING_STATUS_EMAIL_POLLER_METADATA_FIXED_DELAY_IN_SECOND:10}
  kafka:
    bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    emailNotificationTopic: ${KAFKA_EMAIL_NOTIFICATION_TOPIC:email-notification}

