CREATE TABLE SPRING_INTEGRATION_API_APP_ADM.EMAILS
(
    ID                 BIGINT        NOT NULL,
    SENDER_ID          BIGINT        NOT NULL,
    SENDER_NAME        VARCHAR(250)  NOT NULL,
    SUBJECT            VARCHAR(250)  NOT NULL,
    MESSAGE            VARCHAR(4000) NOT NULL,
    ATTACHMENT         VARCHAR(4000),
    RECIPIENT_EMAIL    VARCHAR(250)  NOT NULL,
    RETRY_COUNT        INTEGER,
    SEND_DATE          DATE,
    SEND_STATUS        VARCHAR(100)  NOT NULL,
    CREATED_DATE       DATE          NOT NULL,
    LAST_MODIFIED_DATE DATE          NOT NULL,
    CONSTRAINT EMAILS_PK PRIMARY KEY (ID)
);

CREATE INDEX emails_idx ON SPRING_INTEGRATION_API_APP_ADM.EMAILS (SENDER_ID ASC);

CREATE SEQUENCE SPRING_INTEGRATION_API_APP_ADM.EMAILS_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CYCLE;